name: Sorozaza Root Fix

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4

      - name: MinGW Kurulumu
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Derleme Islemi
        run: |
          # Enjektörü en sade haliyle derle
          g++ injector.cpp -o injector.exe -m64 -static -lkernel32 -luser32 -lpsapi -s -O3
          # DLL'i derle
          g++ -shared cheat.cpp -o hile.dll -m64 -static -luser32 -lgdi32 -ldwmapi -lpsapi -s -O3

      - name: Paketi Sun
        uses: actions/upload-artifact@v4
        with:
          name: Sorozaza_Stable_Pack
          path: |
            injector.exe
            hile.dll
            
