name: C++ Build and Export Exe

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    # MSVC Geliştirici Komut Satırı Ortamını Yükler
    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64 # 64-bit mimari için derleme yapar

    # cl.exe ile kaynak kodunu derler ve .exe üretir
    - name: C++ Kodunu Derle
      run: |
        cl.exe /EHsc main.cpp /Fe:Uygulama.exe

    # =======================================================================
    # .EXE DOSYASINI ARTIFACT OLARAK YÜKLEME (İNDİRİLEBİLİR YAPMA)
    # =======================================================================
    - name: Derlenen Exe Dosyasini Yukle
      uses: actions/upload-artifact@v4
      with:
        name: Derlenmiş-Uygulama       # GitHub panelinde görünecek zip dosyasının adı
        path: Uygulama.exe             # Sanal makinede üretilen ve indirilecek olan dosyanın yolu
        
