name: VS Build

on: [push]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    # Microsoft'un resmi MSBuild kurulum aksiyonu
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Projeyi NuGet paketleri bağımlılığı varsa geri yükle (Opsiyonel)
    #- name: Restore NuGet Packages
    #  run: nuget restore ProjeAdi.sln

    # Çözüm dosyasını derle
    - name: Build Solution
      run: msbuild ProjeAdi.sln /p:Configuration=Release /p:Platform=x64
      
